behaviors:
  Centipede:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800 
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 2048
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 25000000
    time_horizon: 1000
    summary_freq: 10000
